### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dfdfdfs** [kokonguyen191/Il2cppPatcher#5]
Hey. I downloaded this game  アリス・ギア・アイギス 1.34.0

Crash 

C:\dfdfd>java -jar Il2cppPatcher.jar libil2cpp.so dump.cs modding_guide_new.txt
java.lang.NumberFormatException: For input string: "FFFFFFFF80000000"
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at doge.data.Function.parseFunctionAddress(Function.java:73)
        at doge.data.Function.parseFunction(Function.java:38)
        at doge.parser.DumpParser.addFunction(DumpParser.java:76)
        at doge.parser.DumpParser.populateMap(DumpParser.java:62)
        at doge.parser.DumpParser.initialize(DumpParser.java:39)
        at doge.parser.DumpParser.<init>(DumpParser.java:30)
        at doge.Main.run(Main.java:34)
        at doge.Main.main(Main.java:20)
Exception in thread "main" java.lang.NullPointerException
        at doge.patcher.FilePatcher.getNewOffset(FilePatcher.java:121)
        at doge.parser.FileVerifier.isFileAndNewPatchMatched(FileVerifier.java:113)
        at doge.parser.FileVerifier.isFileAndNewModMatched(FileVerifier.java:71)
        at doge.patcher.FilePatcher.writeAllPatchesInOneMod(FilePatcher.java:25)
        at doge.Main.run(Main.java:39)
        at doge.Main.main(Main.java:20)

**Comment by kokonguyen191** [comment]
Sorry I'm not maintaining this tool anymore
